<?php
/**
 * @license All rights reserved
 * @author Guirec Lefort <g.lefort@monsieurbiz.com>
 * @copyright Copyright (c) 2017 Monsieur Biz (https://monsieurbiz.com/)
 */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
/* Get base url with index When index.php enable at Url */
$baseUrl = $storeManager->getStore()->getBaseUrl();

?>
<?php if ($crumbs && is_array($crumbs)): ?>
<div class="container">
    <ol class="breadcrumb" itemscope="" itemtype="http://schema.org/BreadcrumbList">
        <?php $_crumbsCount = 1; ?>
        <?php foreach ($crumbs as $crumbName => $crumbInfo): ?>
            <li class="breadcrumb__item" itemscope="" itemprop="itemListElement" itemtype="http://schema.org/ListItem">
                <?php if ($crumbInfo['link']): ?>
                    <?php if($_crumbsCount!=3): ?>
                        <a href="<?php echo $crumbInfo['link']; ?>" itemprop="item">
                    <?php endif; ?>
                        <span itemprop="name"><?php echo $block->escapeHtml($crumbInfo['label']); ?></span>
                    <?php  if($_crumbsCount!=3): ?>
                        </a>
                    <?php endif; ?>
                <?php elseif ($crumbInfo['last']): ?>
                    <strong itemprop="item">
                        <span class="test" itemprop="name"><?php echo $block->escapeHtml($crumbInfo['label']); ?></span>
                    </strong>
                <?php else: ?>
                    <span itemprop="item">
                        <a href="<?php echo $baseUrl; ?>"><span itemprop="name"><?php echo $block->escapeHtml($crumbInfo['label']); ?></span></a>
                    </span>
                <?php endif; ?>
                <meta itemprop="position" content="<?php echo $_crumbsCount; ?>">
                <?php $_crumbsCount++; ?>
            </li>
        <?php endforeach; ?>
    </ol>
</div>
<?php endif; ?>
