<?php
/**
 * @license All rights reserved
 * @author Maxime Huran <m.huran@monsieurbiz.com> <@MaximeHuran>
 * @copyright Copyright (c) 2017 Monsieur Biz (https://monsieurbiz.com/)
 */
/**
 * Pager template
 *
 * @see \Magento\Theme\Block\Html\Pager
 */
?>
<?php if ($block->getCollection()->getSize()): ?>
    <?php if ($block->getUseContainer()): ?>
        <div class="container">
    <?php endif ?>

    <?php if ($block->getLastPageNum() > 1): ?>
        <nav class="pagination" role="navigation">
            <ul class="pagination__list" itemscope itemtype="http://schema.org/SiteNavigationElement">
                <?php if (!$block->isFirstPage()): ?>
                    <li class="pagination__item pagination__item--previous">
                        <a href="<?php /* @escapeNotVerified */ echo $block->getPreviousPageUrl(); ?>" itemprop="url">
                            <span itemprop="name"><?php /* @escapeNotVerified */ echo __('Previous page'); ?></span>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="pagination__item pagination__item--previous">
                        <span itemprop="name"><?php /* @escapeNotVerified */ echo __('Previous page'); ?></span>
                    </li>
                <?php endif; ?>

                <?php if ($block->canShowFirst()): ?>
                    <li class="pagination__item">
                        <a href="<?php /* @escapeNotVerified */ echo $block->getFirstPageUrl(); ?>" itemprop="url">
                            <span itemprop="name">
                                <em><?php /* @escapeNotVerified */ echo __('Page') ?></em>
                                1
                            </span>
                        </a>
                    </li>
                <?php endif; ?>

                <?php if ($block->canShowPreviousJump()): ?>
                    <li class="pagination__item">
                        <a href="<?php /* @escapeNotVerified */ echo $block->getPreviousJumpUrl(); ?>" itemprop="url">
                            <span itemprop="name">&hellip;</span>
                        </a>
                    </li>
                <?php endif; ?>

                <?php foreach ($block->getFramePages() as $_page): ?>
                    <?php if ($block->isPageCurrent($_page)): ?>
                        <li class="pagination__item pagination__item--active">
                            <span itemprop="name">
                                <em><?php /* @escapeNotVerified */ echo __('Page') ?></em>
                                <?php /* @escapeNotVerified */ echo $_page ?>
                            </span>
                        </li>
                    <?php else: ?>
                        <li class="pagination__item">
                            <a href="<?php /* @escapeNotVerified */ echo $block->getPageUrl($_page); ?>" itemprop="url">
                                <span itemprop="name"><?php /* @escapeNotVerified */ echo $_page; ?></span>
                            </a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>

                <?php if ($block->canShowNextJump()): ?>
                    <li class="pagination__item">
                        <a href="<?php /* @escapeNotVerified */ echo $block->getNextJumpUrl(); ?>" itemprop="url">
                            <span itemprop="name">&hellip;</span>
                        </a>
                    </li>
                <?php endif; ?>

                <?php if ($block->canShowLast()): ?>
                    <li class="pagination__item">
                        <a href="<?php /* @escapeNotVerified */ echo $block->getLastPageUrl(); ?>" itemprop="url">
                            <span itemprop="name">
                                <em><?php /* @escapeNotVerified */ echo __('Page'); ?></em>
                                <?php /* @escapeNotVerified */ echo $block->getLastPageNum(); ?>
                            </span>
                        </a>
                    </li>
                <?php endif; ?>

                <?php if (!$block->isLastPage()): ?>
                    <li class="pagination__item pagination__item--next">
                        <a href="<?php /* @escapeNotVerified */ echo $block->getNextPageUrl(); ?>" itemprop="url">
                            <span itemprop="name"><?php /* @escapeNotVerified */ echo __('Next page'); ?></span>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="pagination__item pagination__item--next">
                        <span itemprop="name"><?php /* @escapeNotVerified */ echo __('Next page'); ?></span>
                    </li>
                <?php endif; ?>
            </ul>
        </nav>
    <?php endif; ?>

    <?php if ($block->getUseContainer()): ?>
        </div>
    <?php endif ?>
<?php endif; ?>
