<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

$productId = $block->getSaleableItem()->getId();

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;


$_product = $block->getSaleableItem();
$finalPrice = $finalPriceModel->getAmount()->getValue();
$originalPrice =  (float) ($_product->getPpc() ?? $priceModel->getAmount()->getValue());
$basePrice = $priceModel->getCustomAmount($originalPrice)->getValue();

?>
<?php if ($finalPrice < $priceModel->getAmount()->getValue()): ?>
    <?php $percent = (1 - $finalPrice / $basePrice) * 100; ?>

    <span class="catalog-product__promotion">
        <?php echo sprintf(__('- %d %% off'), $percent); ?>
    </span>
    <div class="catalog-product__price-container">
        <div class="catalog-product__price catalog-product__price--withpromotion">
            <span class="catalog-product__price-special">
                <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
                    'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                    'price_type'        => 'finalPrice',
                    'include_container' => true,
                    'schema' => $schema
                ]); ?>
                <span class="price-ttc">TTC</span>
            </span>
            <span class="catalog-product__price-old">
                <?php
                $oldPrice =  $block->renderAmount($priceModel->getCustomAmount($originalPrice), [
                    'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                    'price_type'        => 'oldPrice',
                    'include_container' => true,
                    'skip_adjustments'  => true
                ]);
                echo sprintf(__('Instead of <em>%s</em> TTC'), $oldPrice);
                ?>
            </span>
        </div>
    </div>
<?php else: ?>
    <div class="catalog-product__price-container">
        <div class="catalog-product__price">
            <span class="catalog-product__price-final">
                <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
                    'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                    'price_type'        => 'finalPrice',
                    'include_container' => true,
                    'schema' => $schema
                ]); ?><span class="price-ttc">TTC</span>
            </span>
            <span class="catalog-product__price-old">
                <?php
                $oldPrice =  $block->renderAmount($priceModel->getCustomAmount($originalPrice), [
                    'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                    'price_type'        => 'oldPrice',
                    'include_container' => true,
                    'skip_adjustments'  => true
                ]);
                echo sprintf(__('Instead of <em>%s</em>'), $oldPrice);
                ?>
                <span class="old-price-ttc">&nbsp; TTC</span>
            </span>
        </div>
    </div>
<?php endif; ?>

<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()): ?>
        <a href="<?php /* @escapeNotVerified */ echo $block->getSaleableItem()->getProductUrl(); ?>" class="minimal-price-link">
            <?php /* @escapeNotVerified */ echo $block->renderAmountMinimal(); ?>
        </a>
    <?php else: ?>
        <span class="minimal-price-link">
            <?php /* @escapeNotVerified */ echo $block->renderAmountMinimal(); ?>
        </span>
    <?php endif; ?>
<?php endif; ?>
