<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$_rapidotoHelper = $this->helper('Rapidoto\Catalog\Helper\Data');
$productAvailability = $_rapidotoHelper->getProductAvailability($_product->getId());
?>
<?php if (in_array(
    $_product->getTypeId(),
    [
        \Magento\Catalog\Model\Product\Type::TYPE_SIMPLE,
        \Rapidoto\SimplePlain\Model\Product\Type\SimplePlain::TYPE_CODE,
    ]
)): ?>
    <?php
    // Get block with price, availability and add to cart
    echo $block->getChildBlock('product.actions')
        ->setProduct($_product)
        ->setProductAvailability($productAvailability)
        ->toHtml();
    ?>
<?php else : ?>

    <?php echo $block->getChildHtml('product.price.final'); ?>

    <div class="product-add-form">
        <form action="<?php /* @escapeNotVerified */ echo $block->getSubmitUrl($_product) ?>" method="post"
              id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $_product->getId() ?>" />
            <input type="hidden" name="selected_configurable_option" value="" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
            <?php echo $block->getBlockHtml('formkey')?>
            <?php echo $block->getChildHtml('form_top'); ?>
            <?php if (!$block->hasOptions()):?>
                <?php echo $block->getChildHtml('product_info_form_content'); ?>
            <?php else:?>
                <?php if ($_product->isSaleable() && $block->getOptionsContainer() == 'container1'):?>
                    <?php echo $block->getChildChildHtml('options_container') ?>
                <?php endif;?>
            <?php endif; ?>

            <?php if ($_product->isSaleable() && $block->hasOptions() && $block->getOptionsContainer() == 'container2'):?>
                <?php echo $block->getChildChildHtml('options_container') ?>
            <?php endif;?>
            <?php echo $block->getChildHtml('form_bottom'); ?>
    </div>
    <script>
        require([
            'jquery',
            'priceBox'
        ], function($){
            var dataPriceBoxSelector = '[data-role=priceBox]',
                dataProductIdSelector = '[data-product-id=<?php echo $block->escapeHtml($_product->getId())?>]',
                priceBoxes = $(dataPriceBoxSelector + dataProductIdSelector);

            priceBoxes = priceBoxes.filter(function(index, elem){
                return !$(elem).find('.price-from').length;
            });

            priceBoxes.priceBox({'priceConfig': <?php /* @escapeNotVerified */ echo $block->getJsonConfig() ?>});
        });
    </script>
<?php endif; ?>