<?php
/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
$images = json_decode($this->getGalleryImagesJson());
?>
<div id="product-media" class="catalog-product__media">
    <?php foreach($images as $image) : ?>
        <div class="catalog-product__media-item">
            <img src="<?php echo $image->img; ?>" alt="<?php echo $this->getProduct()->getName(); ?>" width="<?php echo $block->getImageAttribute('product_page_image_medium', 'width'); ?>" height="<?php echo $block->getImageAttribute('product_page_image_medium', 'height'); ?>"/>
        </div>
    <?php endforeach; ?>
</div>
