<?php
/**
 * @license All rights reserved
 * @author Guirec Lefort <g.lefort@monsieurbiz.com>
 * @copyright Copyright (c) 2017 Monsieur Biz (https://monsieurbiz.com/)
 */

/**
 * Link catalog template
 *
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<li class="header-links__item header-links__item--catalog">
    <a href="<?php /* @escapeNotVerified */ echo $block->getUrl('catalogue'); ?>">
        <svg class="icon" aria-hidden="true">
            <use xlink:href="<?php echo $this->getViewFileUrl('images/icons.svg#icon-catalog'); ?>"></use>
        </svg>
        <span class="text"><?php echo __('The catalog'); ?></span>
    </a>
</li>
