<?php
/**
 * @license All rights reserved
 * @author Guirec Lefort <g.lefort@monsieurbiz.com>
 * @copyright Copyright (c) 2017 Monsieur Biz (https://monsieurbiz.com/)
 */

/**
 * Logo template
 *
 * @var $block \Magento\Framework\View\Element\Template
 */

$_logoTag = $block->isHomePage() ? 'h1' : 'strong';
$_storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();
?>
<?php echo '<'.$_logoTag.' class="header-logo">'; ?>
    <a href="<?php echo $block->getUrl(); ?>" title="<?php echo $_storeName; ?>">
        <?php echo $_storeName; ?>
    </a>
<?php echo '</'.$_logoTag.'>'; ?>
