<?php
/**
 * @license All rights reserved
 * @author Guirec Lefort <g.lefort@monsieurbiz.com>
 * @copyright Copyright (c) 2017 Monsieur Biz (https://monsieurbiz.com/)
 */

/**
 * Toggle template
 *
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<button id="header-toggle-panel" class="header-toggle" type="button" aria-haspopup="true" aria-expanded="false" aria-controls="header-main">
    <span><?php echo __('Toogle navigation'); ?></span>
</button>
