<?php
/**
 * @license All rights reserved
 * @author Guirec Lefort <g.lefort@monsieurbiz.com>
 * @copyright Copyright (c) 2017 Monsieur Biz (https://monsieurbiz.com/)
 */

/**
 * Utils template
 *
 * @var $block \Magento\Framework\View\Element\Template
 */

// @TODO: Add links
?>
<div class="header-utils">
    <ul class="header-utils__list">
        <li class="header-utils__item">
            <a href="/rapidoto"><?php echo __('Rapidoto?'); ?></a>
        </li>
        <li class="header-utils__item">
            <a href="/nos-engagements"><?php echo __('Our engagements'); ?></a>
        </li>
        <li class="header-utils__item">
            <a href="/comment-passer-commande"><?php echo __('How to place an order'); ?></a>
        </li>
    </ul>
</div>
