<?php
/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */

$storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();
?>
<div class="container">
    <div class="logo">
        <img src="<?php echo $block->getViewFileUrl('images/logo.png'); ?>"
            alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt(); ?>"
            width="308";
            height="55";
        />
    </div>
</div>
