<?php
/**
 * @license All rights reserved
 * @author Guirec Lefort <g.lefort@monsieurbiz.com>
 * @copyright Copyright (c) 2017 Monsieur Biz (https://monsieurbiz.com/)
 */
?>
<div data-bind="scope: 'messages'">
    <div data-bind="foreach: { data: cookieMessages, as: 'message' }">
        <div data-bind="attr: {
            class: 'message ' + 'message--' + message.type,
            'data-ui-id': 'message-' + message.type
        }">
            <p data-bind="html: message.text"></p>
        </div>
    </div>
    <div data-bind="foreach: { data: messages().messages, as: 'message' }">
        <div data-bind="attr: {
            class: 'message ' + 'message--' + message.type,
            'data-ui-id': 'message-' + message.type
        }">
            <p data-bind="html: message.text"></p>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                        "messages": {
                            "component": "Magento_Theme/js/view/messages"
                        }
                    }
                }
            }
    }
</script>
